### PR TITLE
Remove unnecessary constraints

### PR DESCRIPTION
**Pull request by debian-janitor**
Remove unnecessary constraints.

This merge proposal was created automatically by the [Janitor bot](https://janitor.debian.net/scrub-obsolete).
For more information, including instructions on how to disable
these merge proposals, see https://janitor.debian.net/scrub-obsolete.

You can follow up to this merge proposal as you normally would.

The bot will automatically update the merge proposal to resolve merge conflicts
or close the merge proposal when all changes are applied through other means
(e.g. cherry-picks). Updates may take several hours to propagate.

Build and test logs for this branch can be found at
https://janitor.debian.net/scrub-obsolete/pkg/capnproto/f7bef5ba-244f-4b07-8203-9fcf62951fd7.

These changes have no impact on the [binary debdiff](
https://janitor.debian.net/api/run/f7bef5ba-244f-4b07-8203-9fcf62951fd7/debdiff?filter_boring=1).

You can also view the [diffoscope diff](https://janitor.debian.net/api/run/f7bef5ba-244f-4b07-8203-9fcf62951fd7/diffoscope?filter_boring=1) ([unfiltered](https://janitor.debian.net/api/run/f7bef5ba-244f-4b07-8203-9fcf62951fd7/diffoscope)).

### CODE REVIEW

**Comment by thomaslee** [comment]
@tmancill I'm confused why this bot opened the PR against `master` given our `debian/control` file. `master` isn't even the default branch per GH and`Vcs-Git` refers to `debian/master` (though maybe it should be `debian/experimental`? little murky.).

**Comment by tmancill** [comment]
@thomaslee I don't know where debian-janitor is configured, but I don't think it knows to look at `Vcs-Git` for the current package in the archive.  And the value of `Vcs-Git` in the `master` branch wouldn't point to the desired branch anyway: https://github.com/thomaslee/capnproto-debian/blob/master/debian/control#L11.

So, just guessing here, but debian-janitor thought at one point that the packaging was in the `master` branch and continues to scan it for suggestions.  My suggestion: delete the `master` branch.

As for having it run against both `debian/master` and `debian/experimental`, l have no idea, except to say that I would prefer `debian/master`, since `debian/experimental` is ephemeral and should be based off of `debian/master`.  That is, if the Janitor makes an appropriate suggestion for `debian/master`, we can merge it into `debian/experimental` (and deal with the changelog conflicts).

**Comment by thomaslee** [comment]
Done, thanks @tmancill

**Comment by jelmer** [comment]
The janitor does use Vcs-Git field. Specifically, it uses the information that vcswatch (https://qa.debian.org/cgi-bin/vcswatch?package=capnproto) provides, which comes from the Vcs-Git field in debian/control. In this specific case, it's probably a matter of data being out of date - it looks like "-b debian/master" was only added recently (in b1dde2bc12f61bac3f84c8b68a15b3d19044a566), and it may have taken a couple of days to trickle through in vcsawtch.

See also https://janitor.debian.net/cupboard/pkg/capnproto/ - new janitor runs should use the updated data.

**Comment by tmancill** [comment]
@jelmer Ah, thank you for the correction.

You mention the change to `debian/master` being recent, but it was almost 4 weeks old at the time the Janitor opened this PR, so you can understand why it felt like "spooky action at a distance."  Is this due to the resources available to run the checks?  When I check the [queue](https://janitor.debian.net/cupboard/queue), I see times in hours, not days.  

Also, thanks for the links.  I will read up Debian Janitor and learn more about it.

**Comment by jelmer** [comment]
@tmancill Yeah, I appreciate that the timing here wasn't great and that made the change a little misleading. The janitor only recently started publishing changes again, which is why this was a change that was almost 4 weeks old. I'm considering what can be done to perhaps double check changes before they are published so we can redo changes like this when things have changed before they end up in a PR.

**Pull request closed without merging**
