### PR TITLE
Trying again with sbuild

### PR DESCRIPTION
**Pull request by thomaslee**

### CODE REVIEW

**Comment by thomaslee** [comment]
@tmancill hm if you look at this failure I think the GH `ubuntu-latest` runner prevents the `runner` user from being added to the `sbuild` group. I've tried both the the `newgrp sbuild` trick and a separate "step" to try and force it (in GH Actions parlance). Both appear to be no-ops.

https://github.com/thomaslee/capnproto-debian/runs/4829406759?check_suite_focus=true

Can you think of anything else I could try?

**Comment by tmancill** [comment]
> @tmancill hm if you look at this failure I think the GH `ubuntu-latest` runner prevents the `runner` user from being added to the `sbuild` group. I've tried both the the `newgrp sbuild` trick and a separate "step" to try and force it (in GH Actions parlance). Both appear to be no-ops.
> 
> https://github.com/thomaslee/capnproto-debian/runs/4829406759?check_suite_focus=true
> 
> Can you think of anything else I could try?

Maybe it's a limitation of GH Actions?  The first thought that comes to mind is whether you can create a GH Action that creates a new group and successfully adds `runner` to it.  If the answer is "I'm sorry, I can't do that Dave" then at least we know not to pursue the `sbuild` path any further.

Seriously though, I'll have a peek to see if I can figure out how Salsa (running on Gitlab) is doing builds.

**Comment by thomaslee** [comment]
>  The first thought that comes to mind is whether you can create a GH Action that creates a new group and successfully adds runner to it. 

Believe this is basically what `sbuild-adduser` + `newgrp ...` does. And yeah I suspect not being able to modify the GH Actions `runner` user is by design. Just occurred to me to try a `sudo` as a bit of a hail mary, let's see.

**Comment by thomaslee** [comment]
Giving up on this one for now.

**Pull request closed without merging**
