### PR TITLE
Fix OpenSSL 3.0 FTBFS

### PR DESCRIPTION
**Pull request by thomaslee**
@tmancill fyi, work in progress. The test failures are mostly easy but there's something going on with the `TLS client certificate verification` test that I can't figure out at a glance. I'll keep playing with it.

I'm also totally winging it on the BIO_CTRL stuff, the openssl docs seem pretty threadbare on the topic and I'm not familiar with the API. [This](https://github.com/openssl/openssl/issues/14595#issuecomment-801822348) seems to indicate that kTLS can be enabled implicitly if conditions are right and I'm not entirely sure what the implications are for the BIO_CTRL flags (e.g. if kTLS is enabled I'm pretty sure they should be returning `1` but I'm not 100% sure). I'll worry about that after the tests are passing. Ordinarily I wouldn't worry too much but given this is TLS foo feels like it warrants a bit of extra caution.

### CODE REVIEW

**Comment by thomaslee** [comment]
Build command I'm using here if it's interesting/useful:

```
sbuild -d unstable --extra-repository='deb http://deb.debian.org/debian experimental main' --build-dep-resolver=aptitude --add-depends='libssl-dev (>= 3.0.0)' --add-depends='libssl3 (>= 3.0.0)' .
```

**Comment by thomaslee** [comment]
Error for my own reference:

```
[ TEST ] kj/compat/tls-test.c++:710: TLS client certificate verification
kj/compat/tls.c++:66: failed: OpenSSL error; message = error:16000069:STORE routines::unregistered scheme
error:80000002:system library::No such file or directory
stack: ffff8323ba33 ffff832465ab ffff832468b3 ffff83197d27 ffff83197bff aaaabff624d3 aaaabff62663 aaaabff6bb17 ffff8312e1fb
[ FAIL ] kj/compat/tls-test.c++:710: TLS client certificate verification (30588 μs)
```

**Comment by thomaslee** [comment]
Fiddling with libkj's error reporting gave me a little more info:

```
kj/compat/tls.c++:72: failed: OpenSSL error; message = src/kj/compat/tls.c++:329
error:16000069:STORE routines::unregistered scheme, filename=../crypto/store/store_register.c, lineno=237, func=ossl_store_get0_loader_int, data=scheme=file, flags=3
error:80000002:system library::No such file or directory, filename=../providers/implementations/storemgmt/file_store.c, lineno=269, func=file_open, data=calling stat(/usr/lib/ssl/certs), flags=3
stack: ffffbe174d3b ffffbe17fbef ffffbe17fef3 ffffbe0d0d27 ffffbe0d0bff aaaae0780553 aaaae07806e3 aaaae0789c97 ffffbe0671fb
```

So it's complaining about not being able to stat `/usr/lib/ssl/certs` and an unregistered "file" scheme. Not sure if the two errors are related, but they are both part of the same "stack" of errors.

Elsewhere was able to verify the error is occurring in the `Trusted certificate loaded in the client` portion of the failing test.

**Comment by thomaslee** [comment]
Yeah, adding `ca-certificates` to `Build-Depends` fixes the final test failure. Not entirely sure why this happens in 3.0 but doesn't feel totally unreasonable to have at least a build-time dependency on `ca-certificates` just to get through the FTBFS.

@tmancill what do you think RE: adding the `ca-certificates` build dep hack to fix the last test? If that sounds OK I can tidy up this PR and get us building against OpenSSL 3.0.

**Review by tmancill — APPROVED** [review]
@thomaslee This looks great, and I think this is ready for upload to Debian.

I have built against unstable and against experimental (with the magic incantations to get a openssl 3 in the build environment) and also run autopkgtest against both variants.

Also, I think we want to forward your patch upstream.  I checked https://github.com/capnproto/capnproto/issues/ and didn't see the issue reported.  I'm happy to handle that, but don't want to take credit for your patch or intrude upon any existing rapport you may have with upstream.  Just let me know.

**Comment by thomaslee** [comment]
Thanks @tmancill! A few minor changes to make things more consistent and I'll get this merged.

I'm fairly sure the KTLS bioctrls should be okay here, digging around a bit I think it's just used by openssl to query whether capnproto's BIO (OpenSSL's I/O abstraction data type) supports KTLS. Returning zero ("I do not support KTLS") is probably the right thing to do here.

>  Also, I think we want to forward your patch upstream. I checked https://github.com/capnproto/capnproto/issues/ and didn't see the issue reported. I'm happy to handle that, but don't want to take credit for your patch or intrude upon any existing rapport you may have with upstream. Just let me know.

I can run with it, I also want to upstream a patch to improve libkj's out-of-the-box error reporting for OpenSSL because it would have made the original issue much clearer. Of course it's slightly different for OpenSSL 1.1 and 3.0 so a bit of fiddling to do with that. Thanks for the offer!

**Comment by thomaslee** [comment]
`debian/master` is ready for upload when you are @tmancill -- no rush though!

**Comment by tmancill** [comment]
> `debian/master` is ready for upload when you are @tmancill -- no rush though!

ACK that - I've rebuilt against both unstable and experimental and run the autopkgtests on both.  It all looks good.  I'm going to go ahead and apply the tag and push the changelog entry, but will hold off on the actual upload for a day, since that should give 0.9.1-3 enough time to land in testing and start the migration.  (If I upload 0.9.1-4 right now, the clock resets.)

**Comment by thomaslee** [comment]
Sounds good to me, thanks!

**Pull request merged**
