### PR TITLE
0.8.0

### PR DESCRIPTION
**Pull request by thomaslee**
0.8.0 packaging here. Notable changes to the packaging:

* Noticed we weren't building libkj-tls and libkj-gzip with the existing `Build-Depends`, so `Build-Depends` now includes `libssl-dev` and `zlib1g-dev`.
* Ignored all `.la` files via `debian/not-installed`. The `dh_missing` output implies this should be a short-term solution. https://wiki.debian.org/ReleaseGoals/LAFileRemoval doesn't make it clear how it should be handled ... perhaps they should be explicitly removed as part of the build?
* Dropped a few patches that were merged upstream.

Once merged I'll also need to push `pristine-tar` and `upstream` branches (automatically updated by `gbp import-orig ...`).

### CODE REVIEW

**Review by tmancill — APPROVED** [review]
@thomaslee The packaging looks good to me.  I used `ratt` to build all of the reverse dependencies and [clickhouse](https://tracker.debian.org/pkg/clickhouse) fails but doesn't fail when built against the current capnproto:

```
cd /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/dbms && /usr/bin/c++  -Ddbms_EXPORTS -I/<<PKGBUILDDIR>>/contrib/cityhash102/include -I/<<PKGBUILDDIR>>/libs/libpocoext/include -I/<<PKGBUILDDIR>>/libs/libmysqlxx/include -I/<<PKGBUILDDIR>>/contrib/libbtrie/include -isystem /<<PKGBUILDDIR>>/contrib/libdivide -isystem /<<PKGBUILDDIR>>/dbms/src -isystem /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/dbms/src -isystem /<<PKGBUILDDIR>>/contrib/libpcg-random/include -isystem /<<PKGBUILDDIR>>/libs/libcommon/include -isystem /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/libs/libcommon/include -isystem /usr/include/metrohash  -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -pipe  -fno-omit-frame-pointer  -Wall  -Wnon-virtual-dtor -Wextra -O2 -g -DNDEBUG -O3  -flto -fno-fat-lto-objects -fPIC   -fno-tree-loop-distribute-patterns -pthread -std=c++17 -o CMakeFiles/dbms.dir/src/Formats/ODBCDriver2BlockOutputStream.cpp.o -c /<<PKGBUILDDIR>>/dbms/src/Formats/ODBCDriver2BlockOutputStream.cpp
/<<PKGBUILDDIR>>/dbms/src/Formats/CapnProtoRowInputStream.cpp: In member function ‘virtual bool DB::CapnProtoRowInputStream::read(DB::MutableColumns&, DB::RowReadExtension&)’:
/<<PKGBUILDDIR>>/dbms/src/Formats/CapnProtoRowInputStream.cpp:226:12: error: ‘UnalignedFlatArrayMessageReader’ is not a member of ‘capnp’; did you mean ‘FlatArrayMessageReader’?
  226 |     capnp::UnalignedFlatArrayMessageReader msg(array);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |            FlatArrayMessageReader
/<<PKGBUILDDIR>>/dbms/src/Formats/CapnProtoRowInputStream.cpp:231:21: error: ‘msg’ was not declared in this scope
  231 |     stack.push_back(msg.getRoot<capnp::DynamicStruct>(root));
      |                     ^~~
/<<PKGBUILDDIR>>/dbms/src/Formats/CapnProtoRowInputStream.cpp:231:53: error: expected primary-expression before ‘>’ token
  231 |     stack.push_back(msg.getRoot<capnp::DynamicStruct>(root));
      |                                                     ^
...
```

So, I propose that you go ahead and merge and get the `pristine-tar` and `upstream` branches pushed along with the updated `upstream/0.8.0` tag, and then we see if we can patch clickhouse to compile against both versions and submit a patch.  Or, we could upload to `experimental` right away and then work on clickhouse.

**Comment by thomaslee** [comment]
Thanks for checking the reverse deps @tmancill. Wasn't aware of `ratt`, looks very cool.

Ugh this is tickling my memory -- do we need to go through the transition process? https://wiki.debian.org/Teams/ReleaseTeam/Transitions

The process was a bit of a black box to me last time I had to do it, but sounds like getting it into experimental might be the way to go based on the above link. Or does the Release Team specifically need to handle this?

Otherwise agree, I'll get this merged later tonight & we can figure out the policy foo out of band. I'll make sure I get upstream/pristine-tar sorted too.

**Comment by tmancill** [comment]
> Thanks for checking the reverse deps @tmancill. Wasn't aware of `ratt`, looks very cool.

It's a great time-saver (and CPU-waster).  I recently used it to build 635 r-deps for an update to one of the libraries in the Debian Java toolchain.  If you do something like that, I'd advise using a chroot with common build-deps - e.g., the JDK - already installed.

> Ugh this is tickling my memory -- do we need to go through the transition process? https://wiki.debian.org/Teams/ReleaseTeam/Transitions
> 
> The process was a bit of a black box to me last time I had to do it, but sounds like getting it into experimental might be the way to go based on the above link. Or does the Release Team specifically need to handle this?

That's the correct link.  I think we do have to go through a transition process due to the SONAME bump, but with only (5) r-deps, it should go pretty smoothly and we can made it painless for the MRDs (maintainers of reverse dependencies).

> Otherwise agree, I'll get this merged later tonight & we can figure out the policy foo out of band. I'll make sure I get upstream/pristine-tar sorted too.

Yeah, the upstream/pristine-tar workflow for new releases for PRs is kind of clunky IMO (and it's no better on Salsa using Gitlab).

**Comment by thomaslee** [comment]
`upstream`, `pristine-tar` branches and `upstream/0.8.0` tag pushed

**Comment by thomaslee** [comment]
I'll take up the clickhouse issue later tonight / tomorrow.

**Pull request merged**
